// generated by react-router-hono-server/dev
//import { WSContext } from 'hono/ws'
import { createHonoServer } from 'react-router-hono-server/bun'

// if you want to store clients, tho some db would be more fitting
//const clients = new Set<WSContext>()

export default await createHonoServer({
	useWebSocket: true,
	configure(app, { upgradeWebSocket }) {
		app.get('/healthcheck', c => c.text('OK'))
	}
})
