// generated by react-router-hono-server/dev
//import { WSContext } from 'hono/ws'
import { Hono } from 'hono'
import { createHonoServer } from 'react-router-hono-server/bun'

// if you want to store clients, tho some db would be more fitting
//const clients = new Set<WSContext>()
const app = new Hono()

app.get('/health', c => c.json({ status: 'ok' }))

export default await createHonoServer({
	app
})
